agents:
  host:
    llm: "openai/gpt-oss-120b"
    temperature: 0.0

  explorer:
    llm: "openai/gpt-oss-120b"
    temperature: 0.0
    agent_type: "mcp_tool_runner"
    agent_tools:
      - "splunk"

  analyst:
    llm: "openai/gpt-oss-120b"
    temperature: 0.4
    agent_type: "mcp_tool_runner"
    agent_tools:
      - "splunk"